# -*- coding: utf-8 -*-
"""Execution_Trade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LpQULkuwoNwSym5heQSii9hOJZTSI_ng
"""

import requests
import json
import pandas as pd
import time
import math
from datetime import datetime

# ==============================================================================
# 1. 환경 설정 (내 계좌 정보 입력)
# ==============================================================================
class Config:
    APP_KEY = "PSX7LJhBkq7NmBPsJ8ODnP5sxkvkuQOiuafm"
    APP_SECRET = "qiXdaLQpoihZ+O6lJkbKte/JXofchwNkDopcVDgYjclv8Hnakp0Dh635gTGvZ6cabymWyzb5jYfcIKwLx/B0rxpuEz96qZMpT97dskP2Mm5Qj6rGRL1YA/odV1xn1yD/BkU78a38ZybLmAVTLyOnsUi0ZZMDmC5UK2MRlya3ImJBQAS7WLU="

    # 계좌번호 (앞 8자리 + 뒤 2자리)
    CANO = "50158215"  # 계좌번호 앞 8자리
    ACNT_PRDT_CD = "01" # 계좌번호 뒤 2자리 (보통 01)

    # 모의투자 도메인 (실전투자는 'https://openapi.koreainvestment.com:9443')
    URL_BASE = "https://openapivts.koreainvestment.com:29443"

    # 총 매수할 금액 (예: 1,000만원)
    # 실제 계좌 예수금을 조회해서 가져올 수도 있지만, 안전하게 금액을 지정하는 것을 추천합니다.
    TOTAL_INVESTMENT_AMOUNT = 10000000

# ==============================================================================
# 2. 한국투자증권 API 클래스
# ==============================================================================
class KisApi:
    def __init__(self):
        self.base_url = Config.URL_BASE
        self.headers = {"content-type": "application/json"}
        self.access_token = self.get_access_token()

    # [인증] 토큰 발급
    def get_access_token(self):
        path = "oauth2/tokenP"
        url = f"{self.base_url}/{path}"
        body = {
            "grant_type": "client_credentials",
            "appkey": Config.APP_KEY,
            "appsecret": Config.APP_SECRET
        }
        res = requests.post(url, headers=self.headers, data=json.dumps(body))

        if res.status_code == 200:
            token = res.json()['access_token']
            print(f"접근 토큰 발급 성공")
            return f"Bearer {token}"
        else:
            print(f"토큰 발급 실패: {res.text}")
            return None

    # [공통] 헤더 생성 (주문/조회 시 필요)
    def get_common_headers(self, tr_id):
        return {
            "authorization": self.access_token,
            "appkey": Config.APP_KEY,
            "appsecret": Config.APP_SECRET,
            "tr_id": tr_id,
            "custtype": "P", # 개인
        }

    # [조회] 주식 현재가 조회 (매수 수량 계산용)
    def get_current_price(self, code):
        path = "uapi/domestic-stock/v1/quotations/inquire-price"
        url = f"{self.base_url}/{path}"

        headers = self.get_common_headers("FHKST01010100") # 현재가 조회 TR ID
        params = {
            "fid_cond_mrkt_div_code": "J", # 주식, ETF 등
            "fid_input_iscd": code # 종목코드
        }

        res = requests.get(url, headers=headers, params=params)
        if res.status_code == 200 and res.json()['rt_cd'] == '0':
            price = int(res.json()['output']['stck_prpr']) # 현재가
            return price
        else:
            print(f"현재가 조회 실패 ({code}): {res.text}")
            return None

    # [주문] 주식 매수 주문 (시장가)
    def buy_stock(self, code, qty):
        path = "uapi/domestic-stock/v1/trading/order-cash"
        url = f"{self.base_url}/{path}"

        # 모의투자 매수 TR ID: VTTC0802U (실전은 TTTC0802U)
        headers = self.get_common_headers("VTTC0802U")

        data = {
            "CANO": Config.CANO,
            "ACNT_PRDT_CD": Config.ACNT_PRDT_CD,
            "PDNO": code,           # 종목코드
            "ORD_DVSN": "01",       # 주문구분 (00:지정가, 01:시장가) -> 모의투자라 시장가로 체결
            "ORD_QTY": str(qty),    # 주문수량
            "ORD_UNPR": "0",        # 주문단가 (시장가는 0)
        }

        res = requests.post(url, headers=headers, data=json.dumps(data))
        return res.json()

# ==============================================================================
# 3. 메인 실행 로직 (CSV 읽기 -> 계산 -> 매수)
# ==============================================================================
def run_auto_buy():
    print("[모의투자] 자동 매수 프로그램을 시작합니다...")

    # 1. API 연결
    kis = KisApi()
    if not kis.access_token:
        return

    # 2. CSV 파일 읽기
    try:
        df = pd.read_csv("buy_list.csv", dtype={'code': str}) # 코드는 문자로 읽기
        print(f"\n매수 리스트 로드 완료: {len(df)}개 종목")
    except FileNotFoundError:
        print("'buy_list.csv' 파일을 찾을 수 없습니다.")
        return

    # 3. 종목별 순회하며 매수
    total_cash = Config.TOTAL_INVESTMENT_AMOUNT
    print(f"총 투자 금액: {total_cash:,.0f}원\n")

    for idx, row in df.iterrows():
        code = row['code']
        weight = row['weight']

        # 종목코드 보정 (혹시 .KS 등이 붙어있다면 제거)
        code = code.split('.')[0]

        # 3-1. 현재가 조회
        current_price = kis.get_current_price(code)
        if current_price is None:
            continue

        # 3-2. 매수 수량 계산 (투자금 * 비중 / 현재가) -> 내림 처리
        target_amount = total_cash * weight
        buy_qty = int(target_amount // current_price)

        if buy_qty <= 0:
            print(f"⚠️ {code}: 주문 가능 수량이 0주입니다. (배정금액: {target_amount:,.0f}원)")
            continue

        print(f"[{idx+1}/{len(df)}] {code} 주문 준비: 현재가 {current_price:,}원 | 목표 {weight*100}% | 수량 {buy_qty}주")

        # 3-3. 매수 주문 실행
        result = kis.buy_stock(code, buy_qty)

        if result['rt_cd'] == '0':
            print(f"   ✅ 매수 주문 성공! (주문번호: {result['output']['ODNO']})")
            # 로그 파일에 기록 (증빙용)
            with open("buy_log.txt", "a", encoding="utf-8") as f:
                f.write(f"{datetime.now()} | 매수성공 | {code} | {buy_qty}주 | {current_price}원\n")
        else:
            print(f"   ❌ 매수 실패: {result['msg1']}")

        # API 과부하 방지를 위한 대기
        time.sleep(0.2)

    print("\n🏁 모든 주문 처리가 완료되었습니다.")

if __name__ == "__main__":
    run_auto_buy()